version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-crawler}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-crawler}
      POSTGRES_DB: ${POSTGRES_DB:-ghstars}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "crawler", "-d", "ghstars"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: