"""add repo tables

Revision ID: 3726456ccdbb
Revises: 6ae46ba7dd8a
Create Date: 2025-04-28 21:00:47.853976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3726456ccdbb'
down_revision: Union[str, None] = '6ae46ba7dd8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repositories',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name_owner', sa.Text(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_owner')
    )
    op.create_table('repo_star_snapshots',
    sa.Column('repo_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('star_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('repo_id', 'snapshot_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_star_snapshots')
    op.drop_table('repositories')
    # ### end Alembic commands ###
