name: crawl-stars

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  crawl:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: crawler
          POSTGRES_PASSWORD: crawler
          POSTGRES_DB: ghstars
        ports: [5432:5432]
        options: >-
          --health-cmd "pg_isready -U crawler -d ghstars" --health-interval 5s --health-retries 5 --health-timeout 5s

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install deps
        run: |
          uv venv .venv
          uv pip install -e .[dev]

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://crawler:crawler@localhost:5432/ghstars
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          . .venv/bin/activate
          alembic upgrade head

      - name: Crawl stars (10k sample)
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          . .venv/bin/activate
          uv run crawl-stars --limit 100000 --batch 100

      - name: Export CSV
        run: |
          . .venv/bin/activate
          psql postgresql://crawler:crawler@localhost:5432/ghstars -c "\copy repo_star_snapshots to stars.csv csv"

      - uses: actions/upload-artifact@v4
        with:
          name: stars-snapshot
          path: stars.csv